version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  user-service:
    build: .
    container_name:  user-service
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/your-database-name?authSource=admin
      - DB=user_db
      - RABBITMQ_URI=amqp://guest:guest@rabbitmq:5672/
